package com.potensic.proxy.api

import io.ktor.http.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import com.potensic.proxy.Log

/** Static Vite/WebUI asset routes, kept separate from drone APIs. */
fun Route.installWebUiRoutes(assetLoader: (String) -> ByteArray?) {
    // Web UI
    get("/") {
        call.response.headers.append(HttpHeaders.CacheControl, "no-store, max-age=0")
        val html = assetLoader("web/index.html")
        if (html != null) {
            call.respondBytes(html, ContentType.Text.Html)
        } else {
            call.respondText("Potensic Proxy v0.1 ÔÇö web UI not found", ContentType.Text.Plain)
        }
        Log.d("[WebServer] GET / served")
    }

    get("/index.html") {
        call.response.headers.append(HttpHeaders.CacheControl, "no-store, max-age=0")
        val html = assetLoader("web/index.html")
        if (html != null) {
            call.respondBytes(html, ContentType.Text.Html)
        } else {
            call.respond(HttpStatusCode.NotFound)
        }
    }

    // Serve static assets generated by Vite (CSS, JS, SVG, Fonts, etc.)
    get("/assets/{fileName...}") {
        val fileName = call.parameters.getAll("fileName")?.joinToString("/") ?: ""
        val bytes = assetLoader("web/assets/$fileName")
        if (bytes != null) {
            val contentType = when {
                fileName.endsWith(".js") -> ContentType.parse("application/javascript")
                fileName.endsWith(".css") -> ContentType.Text.CSS
                fileName.endsWith(".svg") -> ContentType.parse("image/svg+xml")
                fileName.endsWith(".png") -> ContentType.Image.PNG
                fileName.endsWith(".jpg") || fileName.endsWith(".jpeg") -> ContentType.Image.JPEG
                fileName.endsWith(".woff2") -> ContentType.parse("font/woff2")
                fileName.endsWith(".woff") -> ContentType.parse("font/woff")
                fileName.endsWith(".ttf") -> ContentType.parse("font/ttf")
                else -> ContentType.Application.OctetStream
            }
            call.respondBytes(bytes, contentType)
        } else {
            call.respond(HttpStatusCode.NotFound)
        }
    }

    // Serve offline Vue 3 runtime
    get("/vue.global.prod.js") {
        val js = assetLoader("web/vue.global.prod.js")
        if (js != null) {
            call.respondBytes(js, ContentType.parse("application/javascript"))
        } else {
            call.respond(HttpStatusCode.NotFound)
        }
    }
    get("/static/vue.global.prod.js") {
        val js = assetLoader("web/vue.global.prod.js")
        if (js != null) {
            call.respondBytes(js, ContentType.parse("application/javascript"))
        } else {
            call.respond(HttpStatusCode.NotFound)
        }
    }
    get("/vite.svg") {
        val svg = assetLoader("web/vite.svg")
        if (svg != null) {
            call.respondBytes(svg, ContentType.parse("image/svg+xml"))
        } else {
            call.respond(HttpStatusCode.NotFound)
        }
    }

}
