package com.potensic.proxy

import io.ktor.server.application.*
import io.ktor.server.cio.*
import io.ktor.server.engine.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.websocket.*
import io.ktor.http.*
import io.ktor.utils.io.*
import io.ktor.websocket.*
import kotlinx.coroutines.*
import kotlinx.coroutines.Dispatchers
import org.json.JSONObject
import java.util.concurrent.CopyOnWriteArrayList

/**
 * Embedded HTTP + WebSocket server for remote drone control.
 *
 * HTTP endpoints:
 *   GET  /              ÔåÆ Web UI
 *   GET  /api/status    ÔåÆ Connection status + stats
 *   GET  /api/logs      ÔåÆ Log buffer (with ?since=N for polling)
 *   POST /api/connect   ÔåÆ Connect to USB accessory
 *   POST /api/disconnect ÔåÆ Disconnect
 *
 * WebSocket: /ws/control
 *   Send JSON: {"throttle":0, "yaw":0, "pitch":0, "roll":0, "gimbal":0}
 *   Receive JSON: telemetry + log events
 */
class WebServer(
    private val usbManager: UsbAccessoryManager,
    private val videoExtractor: VideoExtractor,
    private val videoDecoder: VideoDecoder,
    private val assetLoader: (String) -> ByteArray?,
) {
    private var server: EmbeddedServer<CIOApplicationEngine, CIOApplicationEngine.Configuration>? = null
    private val wsClients = CopyOnWriteArrayList<DefaultWebSocketSession>()
    private val usbWsClients = CopyOnWriteArrayList<DefaultWebSocketSession>()

    // Current joystick state (updated by WebSocket clients)
    @Volatile var throttle: Short = 0
    @Volatile var yaw: Short = 0
    @Volatile var pitch: Short = 0
    @Volatile var roll: Short = 0
    @Volatile var gimbalTilt: Short = 0
    @Volatile var hasActiveInput: Boolean = false
    @Volatile private var lastInputTime: Long = 0

    fun start(port: Int = 9090) {
        Log.i("[WebServer] Starting on port $port...")
        server = embeddedServer(CIO, port = port) {
            install(WebSockets)
            routing {
                // Web UI
                get("/") {
                    val html = assetLoader("web/index.html")
                    if (html != null) {
                        call.respondBytes(html, ContentType.Text.Html)
                    } else {
                        call.respondText("Potensic Proxy v0.1 ÔÇö web UI not found", ContentType.Text.Plain)
                    }
                    Log.d("[WebServer] GET / served")
                }

                get("/index.html") {
                    val html = assetLoader("web/index.html")
                    if (html != null) {
                        call.respondBytes(html, ContentType.Text.Html)
                    } else {
                        call.respond(HttpStatusCode.NotFound)
                    }
                }

                // Serve static assets generated by Vite (CSS, JS, SVG, Fonts, etc.)
                get("/assets/{fileName...}") {
                    val fileName = call.parameters.getAll("fileName")?.joinToString("/") ?: ""
                    val bytes = assetLoader("web/assets/$fileName")
                    if (bytes != null) {
                        val contentType = when {
                            fileName.endsWith(".js") -> ContentType.parse("application/javascript")
                            fileName.endsWith(".css") -> ContentType.Text.CSS
                            fileName.endsWith(".svg") -> ContentType.parse("image/svg+xml")
                            fileName.endsWith(".png") -> ContentType.Image.PNG
                            fileName.endsWith(".jpg") || fileName.endsWith(".jpeg") -> ContentType.Image.JPEG
                            fileName.endsWith(".woff2") -> ContentType.parse("font/woff2")
                            fileName.endsWith(".woff") -> ContentType.parse("font/woff")
                            fileName.endsWith(".ttf") -> ContentType.parse("font/ttf")
                            else -> ContentType.Application.OctetStream
                        }
                        call.respondBytes(bytes, contentType)
                    } else {
                        call.respond(HttpStatusCode.NotFound)
                    }
                }

                // Serve offline Vue 3 runtime
                get("/vue.global.prod.js") {
                    val js = assetLoader("web/vue.global.prod.js")
                    if (js != null) {
                        call.respondBytes(js, ContentType.parse("application/javascript"))
                    } else {
                        call.respond(HttpStatusCode.NotFound)
                    }
                }
                get("/static/vue.global.prod.js") {
                    val js = assetLoader("web/vue.global.prod.js")
                    if (js != null) {
                        call.respondBytes(js, ContentType.parse("application/javascript"))
                    } else {
                        call.respond(HttpStatusCode.NotFound)
                    }
                }
                get("/vite.svg") {
                    val svg = assetLoader("web/vite.svg")
                    if (svg != null) {
                        call.respondBytes(svg, ContentType.parse("image/svg+xml"))
                    } else {
                        call.respond(HttpStatusCode.NotFound)
                    }
                }

                // USB WebSocket passthrough (bidirectional)
                webSocket("/ws/usb") {
                    usbWsClients.add(this)
                    Log.i("[WebServer] USB WebSocket client connected (total: ${usbWsClients.size})")
                    try {
                        for (frame in incoming) {
                            when (frame) {
                                is Frame.Binary -> {
                                    val bytes = frame.readBytes()
                                    ProxyService.instance?.sendDirectAny(bytes)
                                }
                                is Frame.Text -> {
                                    val text = frame.readText().trim()
                                    try {
                                        val bytes = if (text.startsWith("{")) {
                                            val json = JSONObject(text)
                                            DroneProtocol.hexToBytes(json.getString("hex"))
                                        } else {
                                            DroneProtocol.hexToBytes(text)
                                        }
                                        ProxyService.instance?.sendDirectAny(bytes)
                                    } catch (e: Exception) {
                                        Log.e("[WebServer] /ws/usb parse error: ${e.message}")
                                    }
                                }
                                else -> {}
                            }
                        }
                    } finally {
                        usbWsClients.remove(this)
                        Log.i("[WebServer] USB WebSocket client disconnected")
                    }
                }

                // OPTIONS preflight for all /api endpoints
                options("/api/{tail...}") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    call.response.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, DELETE")
                    call.response.header("Access-Control-Allow-Headers", "*")
                    call.respond(HttpStatusCode.OK)
                }

                // POST raw packet or hex to USB
                post("/api/usb/send") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    val text = call.receiveText().trim()
                    try {
                        val bytes = if (text.startsWith("{")) {
                            val json = JSONObject(text)
                            DroneProtocol.hexToBytes(json.getString("hex"))
                        } else {
                            DroneProtocol.hexToBytes(text)
                        }
                        ProxyService.instance?.sendDirectAny(bytes)
                        call.respondText("""{"success":true,"sentBytes":${bytes.size}}""", ContentType.Application.Json)
                    } catch (e: Exception) {
                        call.respondText("""{"success":false,"error":"${e.message}"}""", ContentType.Application.Json, HttpStatusCode.BadRequest)
                    }
                }

                // H265 Annex B stream (for ffplay or VLC)
                // Usage: ffplay -f hevc http://10.8.0.31:9090/api/video/h265
                get("/api/video/h265") {
                    Log.i("[WebServer] GET /api/video/h265 ÔÇö starting H265 stream")
                    call.respondBytesWriter(contentType = ContentType.Application.OctetStream) {
                        // Wait for IDR sequence to be available (max 30s)
                        var waited = 0
                        while (videoExtractor.lastIdrSequence == null && waited < 30000) {
                            kotlinx.coroutines.delay(100)
                            waited += 100
                        }

                        val idrSeq = videoExtractor.lastIdrSequence
                        if (idrSeq != null) {
                            // Send the full VPS+SPS+PPS+IDR sequence first
                            writeFully(idrSeq)
                            flush()
                            Log.i("[WebServer] H265: sent IDR init sequence ${idrSeq.size} bytes (waited ${waited}ms)")
                        } else {
                            Log.w("[WebServer] H265: no IDR after ${waited}ms, sending fallback VPS+SPS+PPS")
                            writeFully(videoExtractor.getStreamInitBytes())
                            flush()
                        }

                        // Now stream all frames from the queue
                        var framesSent = 0
                        while (true) {
                            val nal = videoExtractor.nalQueue.poll()
                            if (nal != null) {
                                // Re-inject VPS+SPS+PPS before each IDR
                                if (containsNalType(nal.data, 0x26) && videoExtractor.hasStreamInit) {
                                    val reinit = videoExtractor.getStreamInitBytes()
                                    writeFully(reinit)
                                }
                                writeFully(nal.data)
                                flush()
                                framesSent++
                                if (framesSent % 100 == 0) {
                                    Log.d("[WebServer] H265: $framesSent frames streamed")
                                }
                            } else {
                                kotlinx.coroutines.delay(5)
                            }
                        }
                    }
                }

                // Keep old endpoint as alias
                get("/api/video/h264") {
                    call.respondRedirect("/api/video/h265")
                }

                // Dump raw USB data for offline analysis
                get("/api/video/rawdump") {
                    Log.i("[WebServer] GET /api/video/rawdump ÔÇö capturing 5s of raw data")
                    call.respondBytesWriter(contentType = ContentType.Application.OctetStream) {
                        val start = System.currentTimeMillis()
                        val listener = object : UsbAccessoryManager.Listener {
                            override fun onConnected() {}
                            override fun onDisconnected() {}
                            override fun onDataReceived(data: ByteArray, length: Int) {
                                try {
                                    kotlinx.coroutines.runBlocking {
                                        writeFully(data, 0, length)
                                        flush()
                                    }
                                } catch (_: Exception) {}
                            }
                        }
                        // Temporarily add our listener
                        val origListener = usbManager.listener
                        usbManager.listener = object : UsbAccessoryManager.Listener {
                            override fun onConnected() { origListener?.onConnected() }
                            override fun onDisconnected() { origListener?.onDisconnected() }
                            override fun onDataReceived(data: ByteArray, length: Int) {
                                origListener?.onDataReceived(data, length)
                                listener.onDataReceived(data, length)
                            }
                        }
                        // Capture for 5 seconds
                        kotlinx.coroutines.delay(5000)
                        usbManager.listener = origListener
                        Log.i("[WebServer] Raw dump complete (${System.currentTimeMillis() - start}ms)")
                    }
                }

                // MJPEG stream (decoded by Android MediaCodec hardware)
                get("/api/video/mjpeg") {
                    Log.i("[WebServer] GET /api/video/mjpeg ÔÇö starting MJPEG stream")
                    call.response.header("Access-Control-Allow-Origin", "*")
                    call.response.header("Cache-Control", "no-cache, no-store, must-revalidate")
                    // If no frame yet, auto-kickstart video activation
                    if (videoDecoder.lastJpeg == null) {
                        ProxyService.instance?.activateLiveView()
                    }
                    call.respondBytesWriter(contentType = ContentType.parse("multipart/x-mixed-replace; boundary=frame")) {
                        val boundary = "--frame\r\n"
                        var framesSent = 0
                        var lastSentTime = 0L

                        while (true) {
                            val jpeg = videoDecoder.lastJpeg
                            val jpegTime = videoDecoder.lastJpegTime

                            if (jpeg != null && jpegTime > lastSentTime) {
                                // Always send the LATEST frame, skip queue
                                lastSentTime = jpegTime
                                val header = "${boundary}Content-Type: image/jpeg\r\nContent-Length: ${jpeg.size}\r\n\r\n"
                                writeFully(header.toByteArray())
                                writeFully(jpeg)
                                writeFully("\r\n".toByteArray())
                                flush()
                                framesSent++
                                if (framesSent % 50 == 0) {
                                    Log.d("[WebServer] MJPEG: $framesSent frames")
                                }
                            }
                            kotlinx.coroutines.delay(16) // ~60fps max display rate
                        }
                    }
                }

                // Single JPEG snapshot
                get("/api/video/snapshot") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    call.response.header("Cache-Control", "no-cache, no-store, must-revalidate")
                    val jpeg = videoDecoder.lastJpeg
                    if (jpeg != null) {
                        call.respondBytes(jpeg, ContentType.Image.JPEG)
                    } else {
                        ProxyService.instance?.activateLiveView()
                        call.respondText("No frame available", status = HttpStatusCode.ServiceUnavailable)
                    }
                }

                // Telemetry
                get("/api/telemetry") {
                    call.respondText(TelemetryParser.latest.toJson().toString(), ContentType.Application.Json)
                }

                // Flight commands
                post("/api/cmd/takeoff") {
                    // Send multiple times like official app (hold button behavior)
                    CoroutineScope(Dispatchers.IO).launch {
                        repeat(20) {
                            (ProxyService.instance ?: return@launch).sendDirectAny(DroneProtocol.buildTakeoff())
                            kotlinx.coroutines.delay(50)
                        }
                    }
                    call.respondText("""{"cmd":"takeoff","repeats":20}""", ContentType.Application.Json)
                }
                post("/api/cmd/land") {
                    CoroutineScope(Dispatchers.IO).launch {
                        repeat(20) {
                            (ProxyService.instance ?: return@launch).sendDirectAny(DroneProtocol.buildLand())
                            kotlinx.coroutines.delay(50)
                        }
                    }
                    call.respondText("""{"cmd":"land","repeats":20}""", ContentType.Application.Json)
                }
                post("/api/cmd/rth") {
                    CoroutineScope(Dispatchers.IO).launch {
                        repeat(20) {
                            (ProxyService.instance ?: return@launch).sendDirectAny(DroneProtocol.buildRTH())
                            kotlinx.coroutines.delay(50)
                        }
                    }
                    call.respondText("""{"cmd":"rth","repeats":20}""", ContentType.Application.Json)
                }
                post("/api/cmd/emergency") {
                    // Emergency: send immediately and repeatedly
                    CoroutineScope(Dispatchers.IO).launch {
                        repeat(30) {
                            (ProxyService.instance ?: return@launch).sendDirectAny(DroneProtocol.buildEmergencyStop())
                            kotlinx.coroutines.delay(30)
                        }
                    }
                    call.respondText("""{"cmd":"emergency_stop","repeats":30}""", ContentType.Application.Json)
                }
                // Test endpoint: set joystick values via HTTP (bypass WebSocket)
                // Usage: GET /api/test/joy?t=0&y=0&p=0&r=500 (r=500 = roll right)
                get("/api/test/joy") {
                    val t = call.request.queryParameters["t"]?.toShortOrNull() ?: 0
                    val y = call.request.queryParameters["y"]?.toShortOrNull() ?: 0
                    val p = call.request.queryParameters["p"]?.toShortOrNull() ?: 0
                    val r = call.request.queryParameters["r"]?.toShortOrNull() ?: 0
                    throttle = t; yaw = y; pitch = p; roll = r
                    hasActiveInput = (t != 0.toShort() || y != 0.toShort() || p != 0.toShort() || r != 0.toShort())
                    Log.i("[WebServer] TEST JOY: t=$t y=$y p=$p r=$r active=$hasActiveInput")
                    call.respondText("""{"test":"joy","t":$t,"y":$y,"p":$p,"r":$r,"active":$hasActiveInput}""", ContentType.Application.Json)
                }
                post("/api/cmd/photo") {
                    ProxyService.instance?.sendAny(DroneProtocol.buildTakePhoto())
                    call.respondText("""{"cmd":"photo"}""", ContentType.Application.Json)
                }
                post("/api/cmd/record") {
                    ProxyService.instance?.sendAny(DroneProtocol.buildToggleRecord())
                    call.respondText("""{"cmd":"record"}""", ContentType.Application.Json)
                }
                // RF probe control (CMD 5656 / 0x1618 FpvReqFreqParams)
                post("/api/cmd/rf_probe") {
                    val enable = call.request.queryParameters["enable"]?.toBooleanStrictOrNull() ?: true
                    Log.i("[WebServer] POST /api/cmd/rf_probe (enable=$enable)")
                    val packet = DroneProtocol.buildRequestFreqParams(enable)
                    ProxyService.instance?.sendDirectAny(packet)
                    val json = JSONObject().apply {
                        put("cmd", "rf_probe")
                        put("enable", enable)
                        put("sent", true)
                        put("size", packet.size)
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                }
                post("/api/rf/probe") {
                    val enable = call.request.queryParameters["enable"]?.toBooleanStrictOrNull() ?: true
                    Log.i("[WebServer] POST /api/rf/probe (enable=$enable)")
                    val packet = DroneProtocol.buildRequestFreqParams(enable)
                    ProxyService.instance?.sendDirectAny(packet)
                    val json = JSONObject().apply {
                        put("cmd", "rf_probe")
                        put("enable", enable)
                        put("sent", true)
                        put("size", packet.size)
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                }

                // Send raw hex packet to drone
                post("/api/cmd/raw/{hex}") {
                    val hex = call.parameters["hex"] ?: ""
                    val bytes = DroneProtocol.hexToBytes(hex)
                    Log.i("[WebServer] POST /api/cmd/raw ÔÇö sending ${bytes.size} bytes: $hex")
                    ProxyService.instance?.sendDirectAny(bytes)
                    call.respondText("""{"sent":true,"size":${bytes.size}}""", ContentType.Application.Json)
                }

                // Activate LiveView transmission
                post("/api/video/activate") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    Log.i("[WebServer] POST /api/video/activate")
                    ProxyService.instance?.activateLiveView()
                    call.respondText("""{"success":true,"activated":true}""", ContentType.Application.Json)
                }

                // Request IDR frame from drone
                post("/api/video/request-idr") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    Log.i("[WebServer] POST /api/video/request-idr")
                    val idrCmd = DroneProtocol.buildIDRRequest()
                    ProxyService.instance?.sendDirectAny(idrCmd)
                    call.respondText(JSONObject().put("sent", true).put("size", idrCmd.size).toString(), ContentType.Application.Json)
                }

                // Video stats
                get("/api/video/stats") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    val json = JSONObject().apply {
                        put("framesExtracted", videoExtractor.framesExtracted.get())
                        put("iFrames", videoExtractor.iFrames.get())
                        put("pFrames", videoExtractor.pFrames.get())
                        put("decodedFrames", videoDecoder.framesDecoded.get())
                        put("hasJpeg", videoDecoder.lastJpeg != null)
                        put("lastJpegMs", videoDecoder.lastJpegTime)
                        put("width", videoExtractor.lastWidth)
                        put("height", videoExtractor.lastHeight)
                        put("queueSize", videoExtractor.nalQueue.size)
                        put("lastFrameMs", videoExtractor.lastFrameTime)
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                }

                // Status
                get("/api/status") {
                    call.response.header("Access-Control-Allow-Origin", "*")
                    val json = JSONObject().apply {
                        put("connected", usbManager.isConnected || (ProxyService.instance?.wifiTransport?.isConnected == true))
                        put("mode", if (ProxyService.instance?.wifiTransport?.isConnected == true) "wifi" else if (usbManager.isConnected) "usb" else "none")
                        put("bytesSent", usbManager.bytesSent)
                        put("bytesReceived", usbManager.bytesReceived)
                        put("packetsSent", usbManager.packetsSent)
                        put("packetsReceived", usbManager.packetsReceived)
                        put("lastSendMs", usbManager.lastSendTime)
                        put("lastRecvMs", usbManager.lastRecvTime)
                        put("wsClients", wsClients.size)
                        put("usbWsClients", usbWsClients.size)
                        put("joystick", JSONObject().apply {
                            put("throttle", throttle.toInt())
                            put("yaw", yaw.toInt())
                            put("pitch", pitch.toInt())
                            put("roll", roll.toInt())
                            put("gimbal", gimbalTilt.toInt())
                        })
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                    Log.d("[WebServer] GET /api/status ÔåÆ connected=${usbManager.isConnected}")
                }

                // Logs
                get("/api/logs") {
                    val since = call.request.queryParameters["since"]?.toIntOrNull() ?: 0
                    val logs = Log.getBufferSince(since)
                    val json = JSONObject().apply {
                        put("since", since)
                        put("count", logs.size)
                        put("nextIndex", since + logs.size)
                        val arr = org.json.JSONArray()
                        logs.forEach { arr.put(it) }
                        put("lines", arr)
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                }

                // Connect USB
                post("/api/connect") {
                    Log.i("[WebServer] POST /api/connect ÔÇö attempting USB connection")
                    val ok = usbManager.connect()
                    val json = JSONObject().put("success", ok)
                    call.respondText(json.toString(), ContentType.Application.Json)
                }

                // WiFi Direct: send WifiDirectSwitch via USB to activate hotspot
                post("/api/wifi/activate") {
                    Log.i("[WebServer] POST /api/wifi/activate ÔÇö sending WifiDirectSwitch via USB")
                    val cmd = DroneProtocol.buildWifiDirectSwitch(true)
                    ProxyService.instance?.sendDirectAny(cmd)
                    // Send 3 times for reliability
                    CoroutineScope(Dispatchers.IO).launch {
                        repeat(3) {
                            ProxyService.instance?.sendDirectAny(DroneProtocol.buildWifiDirectSwitch(true))
                            kotlinx.coroutines.delay(200)
                        }
                    }
                    call.respondText("""{"cmd":"wifi_activate","sent":true}""", ContentType.Application.Json)
                }

                // WiFi Direct: BLE scan + pairing
                post("/api/wifi/scan") {
                    Log.i("[WebServer] POST /api/wifi/scan ÔÇö starting BLE pairing")
                    val service = ProxyService.instance
                    if (service == null) {
                        call.respondText("""{"error":"service not running"}""", ContentType.Application.Json)
                    } else {
                        service.startBlePairing()
                        call.respondText("""{"status":"scanning"}""", ContentType.Application.Json)
                    }
                }

                // WiFi Direct: connect TCP to drone
                post("/api/wifi/connect") {
                    val ip = call.request.queryParameters["ip"] ?: "192.168.29.1"
                    val port = call.request.queryParameters["port"]?.toIntOrNull() ?: 8889
                    Log.i("[WebServer] POST /api/wifi/connect ÔåÆ $ip:$port")
                    val service = ProxyService.instance
                    if (service == null) {
                        call.respondText("""{"error":"service not running"}""", ContentType.Application.Json)
                    } else {
                        val ok = service.connectWifi(ip, port)
                        call.respondText("""{"success":$ok,"ip":"$ip","port":$port}""", ContentType.Application.Json)
                    }
                }

                // WiFi Direct: status
                get("/api/wifi/status") {
                    val service = ProxyService.instance
                    val wt = service?.wifiTransport
                    val json = JSONObject().apply {
                        put("wifiConnected", wt?.isConnected ?: false)
                        put("usbConnected", usbManager.isConnected)
                        put("mode", if (wt?.isConnected == true) "wifi" else if (usbManager.isConnected) "usb" else "none")
                        put("bleStatus", service?.bleStatus ?: "idle")
                    }
                    call.respondText(json.toString(), ContentType.Application.Json)
                }

                // Disconnect
                post("/api/disconnect") {
                    Log.i("[WebServer] POST /api/disconnect")
                    usbManager.disconnect()
                    call.respondText(JSONObject().put("disconnected", true).toString(), ContentType.Application.Json)
                }

                // WebSocket for raw H265 NAL streaming (decoded by browser WebCodecs)
                webSocket("/ws/video") {
                    Log.i("[WebServer] Video WebSocket client connected")
                    try {
                        while (true) {
                            val nal = videoExtractor.nalQueue.poll()
                            if (nal != null) {
                                // Send binary frame: [1 byte type] [NAL data]
                                // type: 0=P-frame, 1=IDR
                                val frame = ByteArray(1 + nal.data.size)
                                frame[0] = if (nal.isIFrame) 1 else 0
                                System.arraycopy(nal.data, 0, frame, 1, nal.data.size)
                                send(Frame.Binary(true, frame))
                            } else {
                                kotlinx.coroutines.delay(2)
                            }
                        }
                    } finally {
                        Log.i("[WebServer] Video WebSocket client disconnected")
                    }
                }

                // WebSocket for real-time control
                webSocket("/ws/control") {
                    wsClients.add(this)
                    Log.i("[WebServer] WebSocket client connected (total: ${wsClients.size})")

                    try {
                        for (frame in incoming) {
                            if (frame is Frame.Text) {
                                val text = frame.readText()
                                try {
                                    val json = JSONObject(text)
                                    throttle = json.optInt("throttle", 0).toShort()
                                    yaw = json.optInt("yaw", 0).toShort()
                                    pitch = json.optInt("pitch", 0).toShort()
                                    roll = json.optInt("roll", 0).toShort()
                                    gimbalTilt = json.optInt("gimbal", 0).toShort()
                                    lastInputTime = System.currentTimeMillis()
                                    hasActiveInput = (throttle != 0.toShort() || yaw != 0.toShort() || pitch != 0.toShort() || roll != 0.toShort() || gimbalTilt != 0.toShort())

                                    Log.d("[WebServer] WS input: t=$throttle y=$yaw p=$pitch r=$roll g=$gimbalTilt active=$hasActiveInput")
                                } catch (e: Exception) {
                                    Log.e("[WebServer] WS parse error: ${e.message}")
                                }
                            }
                        }
                    } finally {
                        wsClients.remove(this)
                        Log.i("[WebServer] WebSocket client disconnected (remaining: ${wsClients.size})")
                        // Reset joysticks when client disconnects (safety!)
                        throttle = 0; yaw = 0; pitch = 0; roll = 0; gimbalTilt = 0
                        hasActiveInput = false
                        Log.w("[WebServer] Joysticks reset to zero (client disconnected)")
                    }
                }
            }
        }
        server!!.start(wait = false)
        Log.i("[WebServer] Started on port $port")
    }

    /**
     * Broadcast telemetry/events to all WebSocket clients.
     */
    suspend fun broadcast(json: JSONObject) {
        val text = json.toString()
        wsClients.forEach { session ->
            try {
                session.send(Frame.Text(text))
            } catch (_: Exception) {}
        }
    }

    /**
     * Broadcast raw USB data to all connected USB WebSocket clients.
     */
    suspend fun broadcastUsbData(data: ByteArray) {
        if (usbWsClients.isEmpty()) return
        val frame = Frame.Binary(true, data)
        usbWsClients.forEach { session ->
            try {
                session.send(frame)
            } catch (_: Exception) {}
        }
    }

    /**
     * Check if a byte array contains a H265 NAL unit of a specific type.
     */
    private fun containsNalType(data: ByteArray, nalType: Int): Boolean {
        for (i in 0 until data.size - 4) {
            if (data[i] == 0.toByte() && data[i+1] == 0.toByte() && data[i+2] == 0.toByte() && data[i+3] == 1.toByte()) {
                if (i + 4 < data.size && (data[i+4].toInt() and 0xFF) == nalType) return true
            }
        }
        return false
    }

    fun stop() {
        server?.stop(500, 1000)
        server = null
        wsClients.clear()
        usbWsClients.clear()
        Log.i("[WebServer] Stopped")
    }
}

